/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b8b4d176-a8d6-4755-b145-bc3877c216af",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_XwRLnJ8rJ",
    "aws_user_pools_web_client_id": "6otdmpheqe1dptjkdulbqdodin",
    "oauth": {}
};


export default awsmobile;
